eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:61455/eureka/
server:
  port: 6140
spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://47.103.0.246:4399/notus?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
