eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/
server:
  port: 6004
spring:
  application:
    name: manage_hean
  data:
    mongodb:
      uri: mongodb://47.103.0.246:27017/notus