kind: pipline
name: Breeze

steps:
- name: test-service
  image: maven
  volumes:
  - name: dependency
    path: /root/.m2
# - name: configuration
#   path: /drone/src/back-end/src/main/resources/application.yml
  commands:
  - cd project/auth-service
  - mvn clean
  - mvn package
  - echo "test and package auth-service completed ✔✔✔"
