kind: pipline
name: Breeze

steps:
- name: test admin-service
  image: maven
  volumes:
  - name: dependency
    path: /root/.m2
# - name: configuration
#   path: /drone/src/back-end/src/main/resources/application.yml
  commands:
  - cd project/admin-service
  - mvn clean
  - mvn package
  - echo "test and package admin-service completed 🙂🙂🙂"

- name: test hean-service
  image: maven
  volumes:
  - name: dependency
    path: /root/.m2
  commands:
  - cd project/hean-service
  - mvn clean
  - mvn package
  - echo "test and package hean-service completed 🙂🙂🙂"

- name: test user-service
  image: maven
  volumes:
  - name: dependency
    path: /root/.m2
  commands:
  - cd project/user-service
  - mvn clean
  - mvn package
  - echo "test and package user-service completed 🙂🙂🙂"